pets2/config/routes.rb
Pets::Application.routes.draw do
  resources :foster_parents

  resources :line_pets

  resources :considers

  get "foster/index"
  post "foster/agreement"
  post "foster_parents/new"
  resources :pets
 

  root :to =>  'foster#index', :as => 'foster'

end

pets2/app/models/pet.rb
class Pet < ActiveRecord::Base
  has_many :line_pets
  STATUS_TYPES = [ "Available", "Fostered" ]

  before_destroy :ensure_not_referenced_by_any_line_pet

  validates :name, :breed, :age, :habits, :status, :presence  => true
  validates :age, :numericality => {:greater_than => 0.00, :less_than => 30.00}
  validates :image_url, allow_blank: true, :format => {
    :with => %r{.(gif|jpg|png)\z}i,
    :message => 'must be a .gif, .jpg, or .png format.'
  }
  validates :status, inclusion: STATUS_TYPES

  def self.latest
    Pet.order(:updated_at).last
  end


  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_pet
      if line_pets.empty?
        return true
      else
        errors.add(:base, 'Line Pets present')
        return false
      end
    end
end

pets2/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.order(sort_column + " " + sort_direction)
  end
  

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :image_url, :age, :habits, :status)
    end
  
    def sort_column
      Pet.column_names.include?(params[:sort]) ? params[:sort] : "breed"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

pets2/app/helpers/pets_helper.rb
module PetsHelper
end

pets2/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :habits %><br>
    <%= f.text_area :habits, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, Pet::STATUS_TYPES,
                  prompt: 'Select status type' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pets2/app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

pets2/app/views/pets/index.html.erb
<div id="pet_list">

<h1>Pet Listing</h1>
<h3>You can sort by breed or age!</h3>

<table class="pretty">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th><%= sortable "breed" %></th>
      <th><%= sortable "age" %></th>
      <th>Habits</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr class = "<%= cycle('list_line_odd', 'list_line_even') %>">
	
	<td><%= image_tag(pet.image_url, :class => 'list_image', :height => '200px', :width => '150px') %></td>
        <td><%= pet.name %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.age %></td>
        <td><%= pet.habits %></td>
        <td><%= pet.status %></td>
	
	<td class="list_actions">
          <%= link_to 'Show', pet %><br/>
          <%= link_to 'Edit', edit_pet_path(pet) %><br/>
          <%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<br>

<%= link_to 'New Pet', new_pet_path %>

pets2/app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

pets2/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @pet.image_url %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Habits:</strong>
  <%= @pet.habits %>
</p>

<p>
  <strong>Status:</strong>
  <%= @pet.status %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>