pets2/config/routes.rb
Pets::Application.routes.draw do
  resources :foster_parents

  resources :line_pets

  resources :considers

  get "foster/index"
  post "foster/agreement"
  post "foster_parents/new"
  resources :pets
 

  root :to =>  'foster#index', :as => 'foster'

end

pets2/app/controllers/foster_controller.rb
class FosterController < ApplicationController
  include CurrentConsider
  before_action :set_consider
  def index
    @pets = Pet.where(status: 'Available').order(:name).all
  end

  def agreement
    @pet = Pet.find(params[:pet_id])
  end

end

pets2/app/helpers/foster_helper.rb
module FosterHelper
end

pets2/app/views/foster/agreement.html.erb
<h1>Foster Agreement</h1>
<%= image_tag(@pet.image_url, :height => '250px') %><br/>
<h3>You have chosen <%= @pet.name %></h3><br/>
<p>
I agree to provide <%= @pet.name %> with a loving foster home, and to care for my pet as if it were my own child.
</p>

<%= button_to "Confirm", new_foster_parent_path(:pet_id => @pet.id) %>
<%= button_to 'Cancel', foster_path, method: :get %>

pets2/app/views/foster/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Furries Looking for Homes</h1>

<% cache ['foster', Pet.latest] do %>
  <% @pets.each do |pet| %>
    <% cache ['entry', pet] do %>
      <div class="entry">
        <%= image_tag(pet.image_url, :height => '250px') %>
        <h3><%= pet.name %></h3>
        <%= sanitize(pet.habits) %><br/>
        <h4>Age: <%= pet.age %></h4>
        <div class="breed_line">
          <span class="breed">Breed: <%= pet.breed %></span>
          <%= button_to "Foster #{pet.name}", foster_agreement_path(:pet_id => pet.id) %> 
          <%= button_to 'Considering', line_pets_path(pet_id: pet), remote: true %>
        </div><br/>
      </div>
    <% end %>
  <% end %>
<% end %>