pets2/config/routes.rb
Pets::Application.routes.draw do
  resources :foster_parents

  resources :line_pets

  resources :considers

  get "foster/index"
  post "foster/agreement"
  post "foster_parents/new"
  resources :pets
 

  root :to =>  'foster#index', :as => 'foster'

end

pets2/app/models/foster_parent.rb
class FosterParent < ActiveRecord::Base
  belongs_to :pet
end

pets2/app/controllers/foster_parents_controller.rb
class FosterParentsController < ApplicationController
  before_action :set_foster_parent, only: [:show, :edit, :update, :destroy]

  # GET /foster_parents
  # GET /foster_parents.json
  def index
    @foster_parents = FosterParent.all
  end

  # GET /foster_parents/1
  # GET /foster_parents/1.json
  def show
  end

  # GET /foster_parents/new
  def new
    @foster_parent = FosterParent.new
  end

  # GET /foster_parents/1/edit
  def edit
  end

  # POST /foster_parents
  # POST /foster_parents.json
  def create
    @foster_parent = FosterParent.new(foster_parent_params)

    respond_to do |format|
      if @foster_parent.save
        format.html { redirect_to @foster_parent, notice: 'Foster parent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @foster_parent }
      else
        format.html { render action: 'new' }
        format.json { render json: @foster_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foster_parents/1
  # PATCH/PUT /foster_parents/1.json
  def update
    respond_to do |format|
      if @foster_parent.update(foster_parent_params)
        format.html { redirect_to @foster_parent, notice: 'Foster parent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @foster_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foster_parents/1
  # DELETE /foster_parents/1.json
  def destroy
    @foster_parent.destroy
    respond_to do |format|
      format.html { redirect_to foster_parents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foster_parent
      @foster_parent = FosterParent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foster_parent_params
      params.require(:foster_parent).permit(:name, :address, :email, :pet_id)
    end
end

pets2/app/helpers/foster_parents_helper.rb
module FosterParentsHelper
end

pets2/app/views/foster_parents/_form.html.erb
<%= form_for(@foster_parent) do |f| %>
  <% if @foster_parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foster_parent.errors.count, "error") %> prohibited this foster_parent from being saved:</h2>

      <ul>
      <% @foster_parent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, size: 40 %>
  </div>
  <div class="field" hidden value= <%= :pet_id %> >
    <%= f.label :pet_id %><br>
    <%= f.text_field :pet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pets2/app/views/foster_parents/edit.html.erb
<h1>Editing foster_parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @foster_parent %> |
<%= link_to 'Back', foster_parents_path %>

pets2/app/views/foster_parents/index.html.erb
<h1>Listing foster_parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @foster_parents.each do |foster_parent| %>
      <tr>
        <td><%= foster_parent.name %></td>
        <td><%= foster_parent.address %></td>
        <td><%= foster_parent.email %></td>
        <td><%= foster_parent.pet %></td>
        <td><%= link_to 'Show', foster_parent %></td>
        <td><%= link_to 'Edit', edit_foster_parent_path(foster_parent) %></td>
        <td><%= link_to 'Destroy', foster_parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foster parent', new_foster_parent_path %>

pets2/app/views/foster_parents/new.html.erb
<div class="foster_form">
  <fieldset>
    <legend>Please Enter Your Details</legend>
    <%= render 'form' %>
  </fieldset>
</div>

pets2/app/views/foster_parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foster_parent.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @foster_parent.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @foster_parent.email %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @foster_parent.pet %>
</p>

<%= link_to 'Edit', edit_foster_parent_path(@foster_parent) %> |
<%= link_to 'Back', foster_parents_path %>